<script>var page = 3;</script>

<h2>Celebrity</h2>

<div class="row story topic3">
	<div class="col-sm-12">
		<h1>We don't need to defend Beyonce's feminism anymore because we have 'Beyonce'</h1>
		<h3>by Kara Brown</h3>


		<p class="first">I like to argue. I sincerely enjoy the back and forth with a sane adult. Of course, there are some things that I cannot argue about. For example, I can&rsquo;t have a reasonable discussion about the race of Santa Claus because I don&rsquo;t want a stupidity-induced stroke. I can&rsquo;t have another debate asking which is worse—the &ldquo;n-word&rdquo; or &ldquo;cracker&rdquo;—because the answer is in the question. Feminism is another topic I try to stay away from because so many people just don&rsquo;t know what they&rsquo;re talking about. </p>
		<p>But when it comes to Beyonce, I&rsquo;ve always found it hard to walk away from a conversation about her &ldquo;feminist credentials.&rdquo;</p>
		<p>On this planet, there is a woman who truly believes that Lena Dunham and her constant nakedness is feminism, but because Beyonce agreed to be photographed in her underwear, she is hurting feminism. It&rsquo;s difficult not to scream why that&rsquo;s an obvious double standard and lowkey racist, but it's getting hard to keep arguing with people about this. Thankfully, with the release of her self-titled fifth album, Beyonce tackled head-on almost everything she&rsquo;s been criticized for and, in particular, her being a feminist. </p>
		<p>The morning after Beyonce surprised the world with a midnight record release, I got into a debate on Twitter with someone who called the album &ldquo;sexually frustrated.&rdquo; This LP is sexually frustrated only if you choose to believe that the sexuality she puts on display in songs like &ldquo;Blow&rdquo; and &ldquo;Partition&rdquo; is a reaction to being unhappy or unfulfilled sexually. Because of course, if a woman is celebrating her sexuality in a space where no men are present, it must be because she can&rsquo;t get the attention that she wants from them—or one in particular—and needs to put on a show to beg for it. <a class="highlight" data-toggle="modal" data-target="#1">Call me crazy, but if I was sexually frustrated in my marriage I would have a pretty awkward time asking my husband to write a verse about all the great sex we&rsquo;re not having.</a> </p>
		<p>After that, I wished I hadn&rsquo;t said anything because the beauty of Beyonce is that the people who can&rsquo;t see deeper into what Beyonce is saying and showing us, are revealed by the nature of their attacks. I&rsquo;m not having the &ldquo;Is Beyonce really a feminist/a good feminist/the worst thing to ever happen to feminism?&rdquo; discussion with people again. </p>
		<p>Let&rsquo;s first understand two very straightforward things about feminism:</p>

		<ol>
		  <li>We should all be able to agree that the barebone, absolute minimum definition of feminism is the advocacy and support of social, political and economic rights for women equal to those of men. Thassit.</li>
		  <li>We should also be able to recognize that feminism can look different for different women based on race, sexual orientation, class, economic level, nationality, relationship status, etc. This means that two women can be fighting for two very different things and they can both be feminist acts.</li>
		</ol>
		<p>If we&rsquo;re operating in a space that both recognizes these facts and in which Beyonce exists, there is no room for an argument that Beyonce doesn&rsquo;t practice and encourage feminist values. Maybe she doesn&rsquo;t represent your feminism but she speaks quite clearly to a certain understanding of feminism, specifically for many black women.</p>
		<p>Tom Hawking at Flavorwire wrote a predictable, seemingly on purpose, sloppy &ldquo;review&rdquo; of Beyonce. He reserved a special serving of unaware blabbering when discussing &ldquo;***Flawless,&rdquo; writing that &ldquo;[…]her version of empowerment, such as it is, is based on a sort of inherent conservatism, rooted not in compassion and generosity, but instead in materialism, braggadocio, and inescapable narcissism.&rdquo;</p>
		<p>The thing is that compassion and generosity are not the sole hallmarks of feminism. Seems like someone is confusing feminism with charity work.</p>
		<p>If you want to equate self-love with narcissism, please explain that to all of the black girls in this world who struggle to see themselves as beautiful because they live in a society where beauty is almost exclusively presented as white. If Beyonce celebrating and basking in black beauty—and encouraging others to do the same—is narcissistic, then I hope we all are. And let's not even address the argument that Beyonce is conforming to a &ldquo;traditional standard of beauty.&rdquo; Surprise: There are whole lot of black women who jive with a mainstream aesthetic. It doesn&rsquo;t make them less black, it makes the definition of beauty less white.</p>
		<p>Beyonce is practically a celebratory ode to the beauty of her body. A body type that only in the last ten years or so has even been considered enviable. <a class="highlight" data-toggle="modal" data-target="#2">A body type that today is largely associated with a white woman instead of the Latina who helped set the standard.</a> Why do you think Beyonce talks about her ass all the time and has been since 2001?</p>
		<p>Let's pause for a minute to recognize her lyrics are braggadocious because she&rsquo;s understands, like so many women, that if she doesn&rsquo;t hype herself up, no one else will. She must demand recognition because the system is not going to hand it to her. Maybe, the whole point of &quot;***Flawless&quot; is that even after all she&rsquo;s achieved, she doesn&rsquo;t get the respect she deserves and must aggressively assert her greatness to be properly recognized.</p>
		<p>And yet, Hawking continued. &ldquo;Feminism is actually caring about people who are oppressed—women, minorities, the poor,&rdquo; he wrote. &ldquo;It is not spending 99% of your time talking about how great you are and how much hotter you are than other women and how rich you are[…]&rdquo;</p>
		<p>Black women qualify as &ldquo;people who are oppressed.&rdquo; Beyonce proves that she cares about us by actively working to make sure we&rsquo;re represented in her art. And still, Hawking pressed on, writing that &ldquo;the empress isn&rsquo;t naked; she&rsquo;s dressed in shit you could never, ever afford, and she&rsquo;s laughing at you. Bow down, bitches.&rdquo;</p>
		<p>When she first dropped &ldquo;Bow Down,&rdquo; I drew a stupid amount of joy from watching white feminists complain that Beyoncé telling women to bow down is anti-feminist. Beyonce isn&rsquo;t telling me to bow down—she&rsquo;s talking to all the people who refuse to respect her achievements. I don&rsquo;t need to bow down to Beyonce because I&rsquo;m standing right beside her.</p>
		<p>Truthfully, it's hard to listen to people who aren&rsquo;t black women or well-versed in the specific struggles and issues surrounding black womanhood discuss Beyonce&rsquo;s feminism because there is clearly so much that goes over their heads. This is strange, considering 2013 in particular has been a banner year for feminism and the subject has been a constant topic of cultural discussion. This year, women of color have responded to Sheryl Sandburg and explained why her type of feminism is rooted in privilege, black women have pointed out over, and over, that what Miley Cyrus is doing is racist and appropriating black culture, and it was explained that Rihanna&rsquo;s glorification of strippers outside of a male gaze is a good thing.</p>
		<p>In her piece for Slate, &ldquo;Queen of the Filtered Instagram Image, Beyoncé Critiques Our Airbrushed Beauty Culture,&rdquo; Amanda Hess argues that Beyonce contradicts herself by offering a critique of our culture of beauty in &ldquo;Pretty Hurts&rdquo; while turning around and reinforcing it in &ldquo;***Flawless.&rdquo; &ldquo;Beyoncé may by exposing how ridiculous this notion is,&quot; Hess writes. &quot;But we&rsquo;re still meant to believe that she really does &lsquo;wake up like this.&rsquo;&rdquo;</p>
		<p>To suggest that we&rsquo;re supposed to believe Beyoncé wakes up looking flawless with professional hair, makeup, and styling is absurd. We&rsquo;re not meant to believe that because Beyonce doesn&rsquo;t think we&rsquo;re idiots. It&rsquo;s called a hyperbole—posturing to make a point. This is the woman who has a song called &quot;Flaws and All.&quot; It&rsquo;s almost a moot point though because right after Beyonce describes herself as flawless, as with much of her music, she then encourages women to repeat the same affirmation.</p>
		<p>&quot;We flawless, ladies tell 'em</p>
		<p>I woke up like this, I woke up like this</p>
		<p>We flawless, ladies tell 'em</p>
		<p>Say &quot;I look so good tonight&rdquo;</p>
		<p>This is a call and response, and anyone with even a cursory understanding of black music knows this. Beyonce is arguably the only current artist who creates enormously popular music where so much of what she presents is completely outside the experiences and knowledge of a mainstream audience. (I&rsquo;m talking about her singing about twerking back in 2005, patting her weave and of course, &ldquo;Bootylicious.&rdquo;) Her art is rooted in black womanhood—celebrating and stomping, both figuratively and literally, on the systems and individuals that attempt to suppress it.</p>
		<p>Real Colored Girls incited the exact response they were aiming for with &ldquo;The Problem With Beyhive Bottom Bitch Feminism&rdquo; which equates Jay Z and Beyonce&rsquo;s marriage to the relationship between a pimp and his main ho, suggesting that she is &ldquo;complicit in her own commodification.&rdquo; They predictably cite Jay Z&rsquo;s 2000 track, &ldquo;Big Pimpin&rsquo;&rdquo; to support their argument even after he&rsquo;s gone on record admitting that he regrets the song.</p>
		<p>Jay Z and Beyonce are not only partners—they&rsquo;re artists. They both seem to respect each other&rsquo;s creative freedom and expression. I have to imagine that they&rsquo;ve both done or said things in their music that the other doesn&rsquo;t love, but if this is your spouse, the person you face the world with, aren&rsquo;t you supposed to let them be an individual? Jay Z clearly supports Beyonce being her own woman and likewise, Beyonce respects her man. That&rsquo;s not a ho conceding to her pimp. That's adult understanding and compromise.</p>
		<p>Without attempting—or at least trying—to understand what's happening in her music, the message is probably lost on you. The definition of feminism is not limited to the women who look like you. I don&rsquo;t need to defend Beyonce again because this album does that better than ever I could.</p>
		<p><a href="http://noisey.vice.com/blog/beyonce-feminism-new-album" target="_blank">Source</a></p>

	</div>
</div>

<?php 
	$modal[1] = '<h3 class="wrong-assumption">Call me crazy, but if I was sexually frustrated in my marriage I would have a pretty awkward time asking my husband to write a verse about all the great sex we&rsquo;re not having.</h3>
		      	<p>Beyoncé and Jay Z have been playing out their (real or fictional) relationship tensions at least since the 2007 release of “B’Day,” an album that contains “Ring the Alarm” (about an unnamed partner cheating) and “Irreplaceable” (about a breakup) and ends with “Resentment” (again about an unnamed partner cheating). The last time Beyoncé got a Grammys performance, it was to belt Alanis Morissette’s “You Oughta Know” while Jay Z watched from the audience. It would seem that alluding to mistreatment on the public stage is just one way they keep it fun — or keep their relationship universally accessible to fans looking to extrapolate from their music a universal message. As Beyoncé’s music has grown more baroque, so too have the references.</p>
		      	<p class="small">Excerpt from Salon: "Eat the cake, Anna Mae!": Jay Z delivers his Tina Turner lyric at the Grammys, written by Daniel D\'Addario</p>';
    $modal[2] = '<h3 class="wrong-assumption">A body type that today is largely associated with a white woman instead of the Latina who helped set the standard</h3>
    			<p>The "white woman" is referencing Kim Kardashian who is Armenian. This is a contested issue.</p>
    			<p>The Latina is Jennifer Lopez from a vintage vogue shot in the mid-nineties.</p>
    			<p>Is it relevant to the argument to bring these two women in to the discourse?</p>';
?>
