<script>var page = 5;</script>

<h2>Sports</h2>

<div class="row story topic5">
	<div class="col-sm-12">
        
        <h1>Why College Athletes Should Not Be Paid</h1>
        <h3>By <a href="#seymour">Sasha Seymour</a></h3>
        <p>When asked about whether college athletes should be paid for their athletic services, Syracuse&rsquo;s Hall of Fame basketball coach Jim Boeheim simply replied: &quot;That's really the most idiotic suggestion of all time.&rdquo;</p>
        
        <p>While I won&rsquo;t go as far as Coach Boeheim, I do think it is a bad idea to pay student athletes for their on-field performances. This is a question that comes up all the time in discussions of college sports, and so I think it&rsquo;s important to explain the context in which this question normally occurs. It does not come up for Division I non-revenue sports that struggle to fund their athletic programs. It does not come up at the Division II or III level, either. This question of paying student athletes only comes about in the discussion of the sports of football and basketball at major Division I institutions with high-profile, high-income athletics programs. <a class="highlight" data-toggle="modal" data-target="#1">The truth is that only a fraction of college athletics programs are profitable, while most operate at a cost to the institution.</a> However, the argument still exists that because a small fraction of programs receive millions of dollars from athletics, student-athletes should be paid. </p>
        
        <p>The first major problem with this argument is that college athletes are already paid — a lot. <a class="highlight" data-toggle="modal" data-target="#2">Those few students lucky enough to receive full-athletic scholarships have their tuition, room and board, and books all paid for.</a> Depending on the institution, these costs could climb as high as $50,000 per year. This doesn&rsquo;t include the cost of the best coaches, athletic trainers, and <a class="highlight" data-toggle="modal" data-target="#3">sports medicine care that exist</a>, all provided <a class="highlight" data-toggle="modal" data-target="#4">completely free</a> in the best facilities that can be provided. Some athletes still may need help though, especially if they come from very low-income backgrounds. They receive this help through both the NCAA&rsquo;s Student-Athlete Opportunity Fund as well as the federal government&rsquo;s Pell Grants. The Student-Athlete Opportunity Fund is intended to provide direct benefits to student-athletes and their families and it is certainly used, as the SEC distributed an average of $342,197 to each SEC school through the fund in 2012-13. Those athletes who qualify for Pell Grants on a need basis receive up to $5,645 per year deposited directly in their bank account by the federal government. As a result, if we start paying student-athletes, <a class="highlight" data-toggle="modal" data-target="#5">that money will not go toward helping low-income students pay for their needs, because that money is already available.</a></p>
        
        <p>Next, paying student-athletes is inherently unfair to smaller institutions. If we decided to start paying student-athletes, it is apparent that larger schools would be able to pay more. This is certainly going to influence the decision-making process of high school prospects (as many of those in larger institutions calling for payment of student-athletes know) and it absolutely shouldn&rsquo;t. Student-athletes should be free to choose what school is right for them based on which will help them succeed both athletically and academically — <a class="highlight" data-toggle="modal" data-target="#6">not which can pay them the most money</a>. In addition, a large segment of those pulling for payment of student athletes suggest that only football and men&rsquo;s basketball athletes should be paid — because those are the sports that generate most of the revenue (and it would be infeasible and much more expensive to pay all athletes — and similarly unfair to those that generate the revenue). However, if only the athletes involved in men&rsquo;s football and basketball were paid (the only two areas <a class="highlight" data-toggle="modal" data-target="#7">that generate revenue</a>), it would clearly violate federal Title IX law, which stipulates equal compensation for female and male athletes.</p>
        
        <p>However, the most important reason that college athletes should not be paid is because that&rsquo;s not why they are there. College athletes have an incredible opportunity. They are being prepared for a possible professional career in athletics for free, and can also earn an invaluable college degree at the same time. <a class="highlight" data-toggle="modal" data-target="#8">They are first and foremost students</a> &mdash; students who are receiving their access to a college education through participation in sports. That&rsquo;s what separates student-athletes who participate in college athletics and professional athletes who are also students. Without this distinction, we might as well eliminate the college athletics model as a whole.</p>
        
        <p>As such, while I respect those who fight for the rights of student-athletes (I consider myself one of them). I think the argument that student-athletes should be paid is fundamentally wrong. College athletes already are paid — in services, opportunities, education, and fame (<a class="highlight" data-toggle="modal" data-target="#9">as well as straight cash</a>) — and paying them with respect to on-field performance I believe is certainly wrong. &nbsp;It would prove both <a class="highlight" data-toggle="modal" data-target="#10">logistically impossible</a> as well as critically damaging to the idea of what our college athletic system is supposed to be—a place where student-athletes are simply students before athletes.</p>
        <a id="seymour"></a>
        <blockquote>Sasha Seymour is part of the University of North Carolina Class of 2015, majoring in business at the Kenan-Flagler Business School and Global Studies. Seymour has been the lead scorer for the UNC Junior Varsity Basketball team from 2011 - 2013. </blockquote>
    </div>
</div>

<?php 
	$modal[1] = '<h3>The truth is that only a fraction of college athletics programs are profitable, while most operate at a cost to the institution</h3>
    			 <p>While this may be true, only two out of 30 or 40 teams might make money, but it\'s a false equivalency here. Most schools\' football program makes enough money to pay for all of the other teams at the school and still turn a profit for the athletic department. So while that\'s only one team making money, it\'s making A LOT of money...</p>';
	$modal[2] = '<h3>Those few students lucky enough to receive full-athletic scholarships have their tuition, room and board, and books all paid for</h3>
				<p>Does that pale in comparison to the amount of revenue they\'re bringing in, though? Is Johnny Manziel really only worth $50,000 to Texas A&M? What about Jadaveon Clowney at South Carolina? Or Jabari Parker at Duke?</p>';
	$modal[3] = '<h3>sports medicine care that exist</h3>
				<p>To be fair though, these athletes probably wouldn\'t put their bodies through this level of pain and suffering except for college athletics, so really "free sports medicine" care is the least the university can give them back for their efforts, right?</p>';	
	$modal[4] = '<h3>completely free</h3>
				<p>They\'re not free, though. Those facilities cost a lot of money. The Universities collect that money through athletic revenues and donations, all of which are dependent on quality athletes performing well in the revenue sports at that school. So, in a way, aren\'t multiple generations of athletes paying for those facilities with their labor?</p>';		
	$modal[5] = '<h3>that money will not go toward helping low-income students pay for their needs, because that money is already available</h3>
				<p>Not exactly sure what the argument is here... Are you saying that paying athletes won\'t help low income students pay for their needs?</p>';	
	$modal[6] = '<h3>not which can pay them the most money</h3>
				<p>But in a capitalistic country, should an adult (read: 18-year-old or older) not be allowed to make the best career decision for him or herself? If the professional leagues and the NCAA limit when you may enter the draft to become a professional, why is it crazy to think a young adult should be able to take his or her talents to the highest bidder in college? He or she cannot go pro to earn money when he or she wants, so why also limit their earning potential for even more years? Especially when the risk of injury is a real career threat...</p>';
	$modal[7] = '<h3>that generate revenue</h3>
				<p>While this is true at most schools, there are some universities that generate positive revenues from sports other than Football and Basketball. Conversely, for some schools, even their men\'s basketball team does not turn a profit.</p>';	
	$modal[8] = '<h3>They are first and foremost students</h3>
				<p>For some athletes, though, that\'s simply not the case. Many football and basketball players are not first and foremost students — they\'re simply going to class to get grades good enough to carry them until they can leave school for the draft because they will have far more lucrative careers as professional athletes. Do you think Andrew Wiggins from Kansas or Julius Randle at Kentucky are students first and athletes second? Absolutely not. If not for the NBA and NCAA\'s one-and-done rule, they\'d be professional basketball players already.</p>';	
	$modal[9] = '<h3>as well as straight cash</h3>
				<p>Who\'s paying them straight cash? Are you referring to legal payments in cash or illegal "booster handshakes"?</p>';	
	$modal[10] = '<h3>logistically impossible</h3>
				<p>It\'s not logistically impossible — it\'s logistically very easy. it might be highly unfair or morally questionable in your mind, but the logistics of it can be very simple if you want them to be.</p>';	

?>
