<script>var page = 6;</script>

<h2>Sports</h2>

<div class="row story topic6">
	<div class="col-sm-12">
        <h1>Why Athletes Should Be Paid</h2>
        <h3>By <a href="#moss">Benton Moss</a></h3>
        
        <p>Let me be clear before I begin. I am a collegiate athlete who has a very real stake in this argument, although I most likely will never benefit from what may come of the debate. I am not a basketball or football player, which are the two main groups that I will focus my argument on in this piece. However, I feel that it is my duty as a collegiate athlete to speak on behalf of my fellow competitors and athletes who grind daily to become the best athlete between the lines while maintaining a full, rigorous load from their respective college. I also attend the University of North Carolina at Chapel Hill, a school known for its academic rigor and athletic prowess, and find that striking the perfect balance between scholar and athlete can be difficult at times. </p>
        
        <p>Let&rsquo;s start with a few preliminary facts. The average NCAA football player gives up around <a class="highlight" data-toggle="modal" data-target="#1">43 hours per week to the sport</a> – 3 more than the average work week, on top of taking 12-15 hours of class during a semester. Effectively, the equivalent of working two jobs at once, <a class="highlight" data-toggle="modal" data-target="#2">just higher stakes</a>. We&rsquo;re talking millions at stake here for the school. To be exact? <a class="highlight" data-toggle="modal" data-target="#3">Take the University of Alabama</a>. In FY 2013, they <a class="highlight" data-toggle="modal" data-target="#4">earned</a> <a class="highlight" data-toggle="modal" data-target="#5">$143 million in revenue</a>, more than all <a class="highlight" data-toggle="modal" data-target="#6">30 NHL teams and 25 of 30 NBA teams</a>. As collegiate athletes, <a class="highlight" data-toggle="modal" data-target="#7">our social media sites are monitored daily by compliance teams</a> (all for our &ldquo;protection&rdquo; as amateurs, of course). In <a class="highlight" data-toggle="modal" data-target="#8">40 of 50 US states</a>, the top state-paid employee is either a head football or basketball coach for the state university. </p>
        
        <p>Now, to be clear, I am NOT a proponent for athletes to be paid salaries based on performance. I think there is an even better solution. Distorted free markets always result in the capital that would be allocated in equilibrium to another source. &nbsp;Take for example the unbelievable spending on coaches&rsquo; salaries and athletic facilities. The distortion of not allowing players and recruits to be paid what they are worth has <a class="highlight" data-toggle="modal" data-target="#9">simply caused all of the revenues/donors&rsquo; funds to be reallocated into what matters for recruiting top prospects: jerseys, equipment, coaching staffs, etc.</a> The shadow of this arms race is simply the <a class="highlight" data-toggle="modal" data-target="#10">&ldquo;turn my head while a booster slips him a grand.&rdquo;</a> Of course, this already happens at many large programs and has been well documented. It&rsquo;s a crime to act as if the NCAA is &ldquo;protecting&rsquo; athletes&rsquo; amateur status by dictating that athletes sign their rights away (indeed, the rights to their very name) as the NCAA not-so-silently exploits them on and off the field for over <a class="highlight" data-toggle="modal" data-target="#11">$11 billion in revenues per year</a>. To return to my proposed solution, I believe free markets work best when they are responsive like the stock market. So, in sports, where does value get created?</p>
        
        <p>At the most basic level, why do sports matter? &nbsp;Because people enjoy them; they are pure entertainment value. So, value comes from fans, and players generate value when they draw fans for the schools. Now, to introduce salaries for teams would be quite complicated because each team would become a functioning professional organization with choices on how to allocate massive budgets for each player (some players get salaries while others only receive scholarships?), which would be a large transition and a potential fiasco. However, I am proposing that the NCAA returns the rights of a player&rsquo;s name to the player – allow paid autographs, royalties from memorabilia, gear, etc. &nbsp;Value originates with fans, and that will be where value should be decided. When a player shows that his talent is exemplary, fans create value by the time and money they spend to see him/her in action, and they will ultimately pay for gear with his/her name on it. &nbsp;This is where I believe athletes are receiving the short end of the stick.</p>
        
        <p>The NCAA will not allow an athlete to profit from his own name and talent. <a class="highlight" data-toggle="modal" data-target="#12">Cartel</a> is the only word that covers this type of behavior. Don&rsquo;t know what that is? &nbsp;Do some reading about antitrust law and the <a class="highlight" data-toggle="modal" data-target="#13">Sherman Antitrust Act</a> dealing with anticompetitive behavior and you&rsquo;ll see that the NCAA is nothing more than a <a class="highlight" data-toggle="modal" data-target="#14">cartel</a> posing as a protective body for the student-athletes. Why can&rsquo;t Johnny &ldquo;Football&rdquo; Manziel sign autographs for money on the side when he brings in revenues (or the money that he alone is responsible for drawing in terms of revenue) north of <a class="highlight" data-toggle="modal" data-target="#15">$1 million</a> for his school while the <a class="highlight" data-toggle="modal" data-target="#16">NCAA</a> can sell jerseys with his name on the back? &nbsp;Notice, the NCAA immediately removed his jersey from their site after Jay Bilas&rsquo; remarks over the incredible notion that the NCAA can profit off of a prime athlete&rsquo;s name while prohibiting such behavior from any individual athlete – protecting his &lsquo;amateur&rsquo; status for the &lsquo;purity&rsquo; of college sports. Right. &nbsp;So, all in all, I believe that athletes should be able to profit off of their own likenesses, names, gear, etc. 43 hours per week is no small commitment. The NCAA ought to start respecting these Saturday gladiators a little more and treat them in a more ethical manner.</p>
        
        <p>All this is to say that the NCAA is indeed holding down market wages of college athletes well below what some of the top prospects are worth to their respective schools. Any way you look at the situation, this is just fact. Now, the argument becomes, is this ethical? &nbsp;Your thoughts and comments are always appreciated and I look forward to hearing what you have to contribute to the discussion!</p>
        <p> </p>
        <p>Benton Moss is part of the University of North Carolina Class of 2015, majoring in economics and business administration at the Kenan-Flagler Business School. Moss is the starting pitcher for the UNC baseball team.</p>
        <p> </p>
        
        
        <p>Why Athletes Should Be Paid</p>
        <p>Let me be clear before I begin. I am a collegiate athlete who has a very real stake in this argument, although I most likely will never benefit from what may come of the debate. I am not a basketball or football player, which are the two main groups that I will focus my argument on in this piece. However, I feel that it is my duty as a collegiate athlete to speak on behalf of my fellow competitors and athletes who grind daily to become the best athlete between the lines while maintaining a full, rigorous load from their respective college. I also attend the University of North Carolina at Chapel Hill, a school known for its academic rigor and athletic prowess, and find that striking the perfect balance between scholar and athlete can be difficult at times. </p>
        
        <p>Let&rsquo;s start with a few preliminary facts. The average NCAA football player gives up around 43 hours per week to the sport – 3 more than the average work week, on top of taking 12-15 hours of class during a semester. Effectively, the equivalent of working two jobs at once, just higher stakes. We&rsquo;re talking millions at stake here for the school. To be exact? Take the University of Alabama. In FY 2013, they earned &nbsp;$143 million in revenue, more than all 30 NHL teams and 25 of 30 NBA teams. As collegiate athletes, our social media sites are monitored daily by compliance teams (all for our &ldquo;protection&rdquo; as amateurs, of course). In 40 of 50 US states, the top state-paid employee is either a head football or basketball coach for the state university. </p>
        
        <p>Now, to be clear, I am NOT a proponent for athletes to be paid salaries based on performance. I think there is an even better solution. Distorted free markets always result in the capital that would be allocated in equilibrium to another source. &nbsp;Take for example the unbelievable spending on coaches&rsquo; salaries and athletic facilities. The distortion of not allowing players and recruits to be paid what they are worth has simply caused all of the revenues/donors&rsquo; funds to be reallocated into what matters for recruiting top prospects: jerseys, equipment, coaching staffs, etc. &nbsp;The shadow of this arms race is simply the &ldquo;turn my head while a booster slips him a grand.&rdquo; Of course, this already happens at many large programs and has been well documented. It&rsquo;s a crime to act as if the NCAA is &ldquo;protecting&rsquo; athletes&rsquo; amateur status by dictating that athletes sign their rights away (indeed, the rights to their very name) as the NCAA not-so-silently exploits them on and off the field for over $11 billion in revenues per year. To return to my proposed solution, I believe free markets work best when they are responsive like the stock market. So, in sports, where does value get created?</p>
        
        <p>At the most basic level, why do sports matter? &nbsp;Because people enjoy them; they are pure entertainment value. So, value comes from fans, and players generate value when they draw fans for the schools. Now, to introduce salaries for teams would be quite complicated because each team would become a functioning professional organization with choices on how to allocate massive budgets for each player (some players get salaries while others only receive scholarships?), which would be a large transition and a potential fiasco. However, I am proposing that the NCAA returns the rights of a player&rsquo;s name to the player – allow paid autographs, royalties from memorabilia, gear, etc. &nbsp;Value originates with fans, and that will be where value should be decided. When a player shows that his talent is exemplary, fans create value by the time and money they spend to see him/her in action, and they will ultimately pay for gear with his/her name on it. &nbsp;This is where I believe athletes are receiving the short end of the stick.</p>
        
        <p>The NCAA will not allow an athlete to profit from his own name and talent. Cartel is the only word that covers this type of behavior. Don&rsquo;t know what that is? &nbsp;Do some reading about antitrust law and the Sherman Antitrust Act dealing with anticompetitive behavior and you&rsquo;ll see that the NCAA is nothing more than a cartel posing as a protective body for the student-athletes. Why can&rsquo;t Johnny &ldquo;Football&rdquo; Manziel sign autographs for money on the side when he brings in revenues (or the money that he alone is responsible for drawing in terms of revenue) north of $1 million for his school while the NCAA can sell jerseys with his name on the back? &nbsp;Notice, the NCAA immediately removed his jersey from their site after Jay Bilas&rsquo; remarks over the incredible notion that the NCAA can profit off of a prime athlete&rsquo;s name while prohibiting such behavior from any individual athlete – protecting his &lsquo;amateur&rsquo; status for the &lsquo;purity&rsquo; of college sports. Right. &nbsp;So, all in all, I believe that athletes should be able to profit off of their own likenesses, names, gear, etc. 43 hours per week is no small commitment. The NCAA ought to start respecting these Saturday gladiators a little more and treat them in a more ethical manner.</p>
        
        <p>All this is to say that the NCAA is indeed holding down market wages of college athletes well below what some of the top prospects are worth to their respective schools. Any way you look at the situation, this is just fact. Now, the argument becomes, is this ethical? &nbsp;Your thoughts and comments are always appreciated and I look forward to hearing what you have to contribute to the discussion!</p>
        <a id="moss"></a>
        <blockquote>Benton Moss is part of the University of North Carolina Class of 2015, majoring in economics and business administration at the Kenan-Flagler Business School. Moss is the starting pitcher for the UNC baseball team.</blockquote>
	</div>
</div>

<?php
	$modal[1] = '<h3>43 hours per week to the sport</h3>
    			<p>The NCAA limits hours spent with a sport to 20 per week. Sure many athletes do voluntary work outside of this, but there is a limit in place. Even realizing they do a lot of work outside of practice, this is a self-reported survey, so it\'s tough to say whether these numbers are actually accurate.</p>';
    $modal[2] = '<h3>just higher stakes</h3>
    			<p>Debatable. While the stakes might be high for universities, the stakes for the individual athlete are probably much lower than someone who has to work two jobs to support himself or his family.</p>';
    $modal[3] = '<h3>Take the University of Alabama</h3>
    			<p>Cherry-picking data. This is an isolated example of a team with a complete monopoly over the state\'s athletic construct.</p>';
    $modal[4] = '<h3>earned</h3>
    			<p>False analogues: It\'s not fair to compare every sport at Alabama vs. one single franchise in the pros.</p>';
	$modal[5] = '<h3>$143 million in revenue</h3>
    			<p>This figure includes a large amount of donations, which are not something that pro sports benefit from. It\'s not fair to compare strict revenue from a professional sport to a non-itemized total revenue figure.</p>';
	$modal[6] = '<h3>30 NHL teams and 25 of 30 NBA teams</h3>
    			<p>Debatable. You\'re strictly talking about revenue, which is generally a false comparison because Alabama is pulling money from a ton of sports, not just one. If you compare profits though, far more professional teams take home more money than Alabama does from its sports teams.</p>';
	$modal[7] = '<h3>our social media sites are monitored daily by compliance teams</h3>
    			<p>How does that apply to the stakes of paying athletes? While I agree this is probably a huge pain in the ass, I don\'t know that it really raises the financial stakes of being a college athlete.</p>';
	$modal[8] = '<h3>40 of 50 US states</h3>
    			<p>While this is true in gross terms, this is not comparing strictly state-based salaries. Most head coaches take in a much smaller percentage of their revenue directly from the state, instead drawing it from a private foundation that supplements salaries for coaches. So while the coaches do make more money than any other state employee in most places, the 40/50 number might not be entirely accurate if you only compare the actual funds coming from the state\'s budget.</p>';
	$modal[9] = '<h3>simply caused all of the revenues/donors’ funds to be reallocated into what matters for recruiting top prospects: jerseys, equipment, coaching staffs, etc</h3>
    			<p>I think you could make a pretty good argument that these institutions would spend this kind of money on coaches, equipment, facilities and jerseys regardless of whether players were paid...</p>';
	$modal[10] = '<h3>turn my head while a booster slips him a grand</h3>
    			<p>Is there any evidence to suggest that this wouldn\'t happen if players were allowed to profit from their endeavors? Would boosters have to now just report that they\'re giving money to these players?</p>';
	$modal[11] = '<h3>$11 billion in revenues per years</h3>
    			<p>I don\'t know where this statistic comes from. USA Today reported about <a href="http://www.usatoday.com/story/sports/college/2013/05/02/ncaa-financial-statement-surplus/2128431/">$850 million in revenues for the NCAA in 2012</a>.</p>';
	$modal[12] = '<h3>Cartel</h3>
    			<p>While the statement is true, athletes cannot currently profit from their own names or likenesses, calling the NCAA a "cartel" might be a bit harsh — no one is dying over territorial disputes here...</p>';
	$modal[13] = '<h3>Sherman Antitrust Act</h3>
    			<p><a target="_blank" href="http://sportsillustrated.cnn.com/college-football/news/20140306/ncaa-lawsuit-scholarship-limit-shawne-alston/">Multiple cases</a> have made their way to federal courts on the Sherman Antitrust grounds against the NCAA and most, if not all, of the previous cases have been decided in the NCAA\'s favor. For antitrust to be proven, you have to establish that the NCAA is acting to stifle competition among schools, which is a really tough argument to make being that the NCAA specifically promotes competition — that\'s their mission, essentially.</p>';
	$modal[14] = '<h3>cartel</h3>
    			<p>Again, there are serious grievances against the NCAA from an anti-trust standpoint, but that\'s no different than many corporations throughout this country\'s history — it does not necessarily denigrate them to the level of "cartel."</p>';
	$modal[15] = '<h3>$1 million</h3>
    			<p>Unknown — While this statistic actually seems low, we were not able to corroborate it independently. Some reports have his media exposure value for Texas A&M up to <a target="_blank" href="http://theweek.com/article/index/247910/how-much-money-has-texas-aampm-made-off-johnny-manziel">$37 million in 2012</a>.</p>';
	$modal[16] = '<h3>NCAA can sell jerseys</h3>
    			<p>The NCAA doesn\'t sell his jerseys, Texas A&M does...</p>';
?>
        
